### ISSUE TITLE
RPLidar Stuck on Startup

### ISSUE THREAD

**Issue by stonier** [yujinrobot/rplidar_extras#2]
* GoCart203
* She's dead Jim
* Lots of nodelet heartbeat warnings at the same time (associated problem)
* No 2D scans, 3d scans fine
* Restarted (not rebooted) and it was fine.
* Making a clunking noise each rotation

**Comment by naveedhd** [comment]
* GoCart204
* RPLidar 2
* She's dead Jim
* Restarted (not rebooted) and it was fine.


*edit: was running the older sources which did not have the [fix for reset](https://github.com/yujinrobot/rplidar_extras/commit/ee09994f9ba0e869310402a6ea3df10b3ce5ce8e).*

**Comment by Marco-Andarcia** [comment]
@naveedhd  is this still an issue? does the fix for reset takes care of this?

**Comment by naveedhd** [comment]
Yes! I think this is the same/similar issue as [this](https://bitbucket.org/yujinrobot/gopher_defcon/issues/357/rplidar-not-publishing-any-data-but-no)
